from . import res_company
from . import res_location
from . import res_serial_range
from . import grz_available_number
from . import stock_lot
from . import product_category
from . import product_category_2
from . import product_template
from . import oe_program
from . import oe_project
from . import repair_fee
from . import repair_order
from . import repair_spare_part_request
from . import repair_transfer_request
from . import repair_return_request