apiVersion: v1
kind: Service
metadata:
  name: oemis-odoo
spec:
  $patch: replace
  type: LoadBalancer
  selector:
    app: oemis-odoo
  ports:
    - name: http
      port: 3000
      targetPort: 8069
