apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oemis-odoo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - staging.oemis.example.com
      secretName: oemis-staging-tls
  rules:
    - host: staging.oemis.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oemis-odoo
                port:
                  number: 8069
